# Generated by Django 4.2 on 2023-04-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='topic',
            new_name='topics',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='users',
        ),
    ]
