# Generated by Django 4.2 on 2023-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blogpost_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug_url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
